spring:
  datasource:
    url: jdbc:sqlserver://localhost:1444;databaseName=dbTheXuong;encrypt=true;trustServerCertificate=true
    username: sa
    password: Vinhledz7479@1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
        provider:
          google:
            user-name-attribute: name
jwt:
  secret: KhoaBiMatPhaiRatDaiDeBaoMatJWTTheXuongProject2024 # > 256 bits
  expiration: 3600000 # 1 gi·ªù